//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int adminId { get; set; }
        public string adminFirstName { get; set; }
        public string adminLastName { get; set; }
        public string adminEmail { get; set; }
        public string adminpassword { get; set; }
    }
}
